### ISSUE TITLE
Can we define root actor action

### ISSUE THREAD

**Issue by vallettea** [untu/comedy#3]
Since all messages are going through the root actor, he may as well achieve some work. Can I define messages and associated function for the root actor ?

**Comment by weekens** [comment]
Yes, you can specify your own actor definition for the root actor by using `root` actor system creation option.

```javascript
var actors = require('comedy');

var actorSystem = actors({
  // Plain-object root actor definition.
  root: {
    myHandler: function() {
      // Message handler implementation.
    }
  }
});
```

or

```javascript
var actors = require('comedy');

class MyRootActor {
  myHandler() {
    // Message handler implementation.
  }
}

var actorSystem = actors({
  // Class-defined root actor.
  root: MyRootActor
});
```

Just like with any actor, you can specify lifecycle hooks - `initialize` and `destroy` - for your custom root actor.

**Comment by weekens** [comment]
It's not usually the case that all messages are going through root actor. Normally, you would try to limit the messaging between the actors and move it down the hierarchy so that the actors that are close to root only delegate big chunks of work to their children without having any knowledge of what's happening in their actor subtree.

A good analogy is a human organization, where the top management only sets high level objectives to the departments, and the departments then work on these objectives by spawning sub-departments, hiring people and doing a lot of intra-department message exchange that top management has no clue about.

**Comment by vallettea** [comment]
Thanks again.
I see this top down structure, but in my case and in most cases that cannot be tackled by a map-reduce pipeline, you sometimes need to go up the hierarchy.
